name: "Deploy to Hostinger"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup SSH key and known hosts
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          set -xe
          mkdir -p $HOME/.ssh
          echo "$DEPLOY_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -p 65002 -H 151.106.96.153 >> $HOME/.ssh/known_hosts

      - name: Execute remote deploy
        run: |
          ssh -i $HOME/.ssh/id_rsa -p 65002 u958695462@151.106.96.153 << 'EOF'
            cd domains/facilitatecnologia.com.br
            git pull origin main
            php artisan migrate --force
            php artisan route:cache
          EOF
